# Generated by Django 5.2.11 on 2026-03-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo_iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('moneda_codigo', models.CharField(max_length=10)),
                ('moneda_nombre', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('ANDINA', 'Andina'), ('CONO_SUR', 'Cono Sur'), ('CENTROAMERICA', 'Centroamerica'), ('CARIBE', 'Caribe')], max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('poblacion', models.BigIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
