# Generated by Django 5.2.11 on 2026-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_pais_options'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicadoreconomico',
            old_name='fecha_carga',
            new_name='fecha_actualizacion',
        ),
        migrations.AlterUniqueTogether(
            name='indicadoreconomico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicadoreconomico',
            name='unidad',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('USD', 'USD'), ('USD_MILES_MILLONES', 'USD Miles de Millones')], default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicadoreconomico',
            name='fuente',
            field=models.CharField(choices=[('WORLD_BANK', 'World Bank'), ('MANUAL', 'Manual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='indicadoreconomico',
            name='tipo',
            field=models.CharField(choices=[('PIB', 'Producto Interno Bruto'), ('INFLACION', 'Inflación'), ('DESEMPLEO', 'Desempleo'), ('BALANZA_COMERCIAL', 'Balanza Comercial'), ('DEUDA_PIB', 'Deuda PIB'), ('PIB_PERCAPITA', 'PIB Percapita')], max_length=20),
        ),
        migrations.AlterField(
            model_name='indicadoreconomico',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AddConstraint(
            model_name='indicadoreconomico',
            constraint=models.UniqueConstraint(fields=('pais', 'tipo', 'anio'), name='unique_indicador_pais_tipo_anio'),
        ),
    ]
