# Generated by Django 5.2 on 2026-03-07 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('countries', '0002_alter_pais_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.pais'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo_alerta',
            field=models.CharField(choices=[('RIESGO', 'Riesgo'), ('TIPO_CAMBIO', 'Tipo Cambio'), ('INDICADOR', 'Indicador'), ('SISTEMA', 'Sistema')], max_length=20),
        ),
    ]
