# Generated by Django 5.2.11 on 2026-03-03 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_alter_pais_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('score_economico', models.FloatField()),
                ('score_cambiario', models.FloatField()),
                ('score_estabilidad', models.FloatField()),
                ('indice_compuesto', models.FloatField()),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('CRITICO', 'Critico')], max_length=20)),
                ('detalle_calculo', models.JSONField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices_riesgo', to='countries.pais')),
            ],
            options={
                'ordering': ['-fecha_calculo'],
                'constraints': [models.CheckConstraint(condition=models.Q(('indice_compuesto__gte', 0), ('indice_compuesto__lte', 100)), name='indice_compuesto_entre_0_100')],
            },
        ),
    ]
