# Generated by Django 5.2.11 on 2026-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_pais_options'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='indiceriesgo',
            index=models.Index(fields=['pais'], name='risk_indice_pais_id_5ba7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='indiceriesgo',
            index=models.Index(fields=['-fecha_calculo'], name='risk_indice_fecha_c_0c37b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='indiceriesgo',
            constraint=models.CheckConstraint(condition=models.Q(('score_economico__gte', 0), ('score_economico__lte', 100)), name='score_economico_entre_0_100'),
        ),
        migrations.AddConstraint(
            model_name='indiceriesgo',
            constraint=models.CheckConstraint(condition=models.Q(('score_cambiario__gte', 0), ('score_cambiario__lte', 100)), name='score_cambiario_entre_0_100'),
        ),
        migrations.AddConstraint(
            model_name='indiceriesgo',
            constraint=models.CheckConstraint(condition=models.Q(('score_estabilidad__gte', 0), ('score_estabilidad__lte', 100)), name='score_estabilidad_entre_0_100'),
        ),
    ]
