# Generated by Django 5.2 on 2026-03-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_indiceriesgo_risk_indice_pais_id_5ba7f4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiceriesgo',
            name='fecha_calculo',
            field=models.DateField(),
        ),
    ]
