# Generated by Django 5.2 on 2026-03-07 07:07

from django.db import migrations, models


def remove_duplicate_riesgo(apps, schema_editor):
    """Remove duplicate IndiceRiesgo entries keeping the latest one per (pais, fecha_calculo)."""
    IndiceRiesgo = apps.get_model('risk', 'IndiceRiesgo')
    seen = set()
    to_delete = []
    for entry in IndiceRiesgo.objects.order_by('pais', 'fecha_calculo', '-id'):
        key = (entry.pais_id, entry.fecha_calculo)
        if key in seen:
            to_delete.append(entry.id)
        else:
            seen.add(key)
    if to_delete:
        IndiceRiesgo.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_pais_options'),
        ('risk', '0003_change_fecha_calculo_to_datefield'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_riesgo, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='indiceriesgo',
            constraint=models.UniqueConstraint(fields=('pais', 'fecha_calculo'), name='unique_riesgo_pais_fecha'),
        ),
    ]
