# Generated by Django 5.2.11 on 2026-03-03 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_alter_pais_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('es_publico', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_activo', models.CharField(choices=[('RENTA_FIJA', 'Renta Fija'), ('RENTA_VARIABLE', 'Renta Variable'), ('COMMODITIES', 'Commodities'), ('MONEDA', 'Moneda')], max_length=20)),
                ('monto_inversion_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.pais')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='portfolios.portafolio')),
            ],
        ),
        migrations.AddConstraint(
            model_name='portafolio',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='unique_portafolio_usuario_nombre'),
        ),
        migrations.AddConstraint(
            model_name='posicion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_salida__isnull', True), ('fecha_salida__gt', models.F('fecha_entrada')), _connector='OR'), name='fecha_salida_mayor_entrada'),
        ),
    ]
