# Generated by Django 5.2.11 on 2026-03-03 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PIB', 'Producto Interno Bruto'), ('INFLACION', 'Inflación'), ('DESEMPLEO', 'Desempleo')], max_length=20)),
                ('anio', models.IntegerField()),
                ('valor', models.FloatField()),
                ('fuente', models.CharField(max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='countries.pais')),
            ],
            options={
                'ordering': ['-anio'],
                'unique_together': {('pais', 'tipo', 'anio')},
            },
        ),
    ]
