# Generated by Django 5.2.11 on 2026-03-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
