# Generated by Django 5.2.11 on 2026-03-03 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_alter_pais_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_destino', models.CharField(default='USD', max_length=10)),
                ('tasa', models.FloatField()),
                ('fecha', models.DateField()),
                ('variacion_porcentual', models.FloatField(blank=True, null=True)),
                ('fuente', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.pais')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('pais', 'fecha')},
            },
        ),
    ]
