# Generated by Django 5.2.11 on 2026-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_pais_options'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipocambio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='tasa',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='tipocambio',
            constraint=models.UniqueConstraint(fields=('pais', 'fecha'), name='unique_tipo_cambio_pais_fecha'),
        ),
    ]
