# Generated by Django 5.2.11 on 2026-03-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_tipocambio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocambio',
            name='tasa',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
