# Generated by Django 5.2.11 on 2026-03-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_pais_options'),
        ('exchange', '0003_alter_tipocambio_tasa'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tipocambio',
            name='unique_tipo_cambio_pais_fecha',
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='tasa',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='variacion_porcentual',
            field=models.FloatField(blank=True, max_length=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='tipocambio',
            constraint=models.UniqueConstraint(fields=('pais', 'moneda_destino', 'fecha'), name='unique_tipo_cambio_pais_fecha'),
        ),
    ]
