# Generated by Django 5.2.11 on 2026-03-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_remove_tipocambio_unique_tipo_cambio_pais_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocambio',
            name='variacion_porcentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
